### ISSUE TITLE
不行，打包启动失败

### ISSUE THREAD

**Issue by Jeffpxf** [freewind-demos/typescript-webpack-exclude-fs-demo#1]
![Uploading fs启动失败.png…]()

**Comment by Jeffpxf** [comment]
> start
> webpack-dev-server --config-register ts-node/register --open

(node:36416) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:434:10)
    at E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:466:5
    at E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:327:12
    at E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:434:10)
    at E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:466:5
    at E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\webpack\lib\NormalModule.js:327:12
    at E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (E:\Users\Jeff\Downloads\typescript-webpack-exclude-fs-demo-master\typescript-webpack-exclude-fs-demo-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
